DROP TABLE PARKING;

CREATE TABLE PARKING (
	CAR_NO 	NUMBER 					NOT NULL,
    NUM     VARCHAR2(99 BYTE)		NOT NULL,
	MODEL 	VARCHAR2(99 BYTE) 		NOT NULL
);

ALTER TABLE PARKING
	ADD CONSTRAINT PK_PARKING PRIMARY KEY(CAR_NO);
	
DROP SEQUENCE PARKING_SEQ;
CREATE SEQUENCE PARKING_SEQ NOCACHE;

SELECT CAR_NO, NUM, MODEL
  FROM PARKING;