DROP TABLE PARKING_TBL;

CREATE TABLE PARKING_TBL (
	CAR_NO 	NUMBER 					NOT NULL,
	MODEL 	VARCHAR2(99 BYTE) 		NOT NULL,
	NUM     NUMBER 					NOT NULL
);

ALTER TABLE PARKING_TBL
	ADD CONSTRAINT PK_PARKING PRIMARY KEY(CAR_NO);
	
DROP SEQUENCE PARKING_SEQ;
CREATE SEQUENCE PARKING_SEQ NOCACHE;

SELECT CAR_NO, MODEL, NUM
  FROM PARKING_TBL;
